### PR TITLE
Ported to 1.18.2 and fixed few bugs

### PR DESCRIPTION
**Pull request by yanang007**
Thanks for your excellent mod! 
This is a 1.18.2 port. Mainly focused on updating dependencies and migrating Minecraft source mappings from 1.16.5 to 1.18.2.

### **Changes**
1. Removed **_FlexCrateRegistry_** as **_AdjustableCrateBlock_** is removed in after Create v0.4.0.
2. Added **_MountedStorageManagerMixin_** to access mounted storage info. **_MountedStorageManager_** is used in Create 1.18.2 to manage mounted inventories.
3. Temporarily removed **_Storage Overhaul_** support () as they do not support 1.18.2 for now.
4. Replaced **_OverWrites_** with **_Injects_** for better compatibility and removed **_OverWrite_** of **_serialize()_**.

There are some details that I'm not sure about:
1. Is Overwriting **_serialize()_** necessary? It seems to work just fine without it.
2. In Create 0.5.0c there is no specific code for Double Chest anymore ([here](https://github.com/Creators-of-Create/Create/blob/82be76d8934af03b4e52cad6a9f74a4175ba7b05/src/main/java/com/simibubi/create/content/contraptions/components/structureMovement/MountedStorage.java#L66-L78)), is **_DoubleChestItemStackHandler_** still necessary? It seems little broken according to my tests, leading to _ArrayIndexOutOfBoundsException_.

### CODE REVIEW

**Comment by yanang007** [comment]
Besides the port, I'm trying to fix some minor bugs and make mixins more portable with newer versions of Create, but I'm not sure whether they are the best practice or not. It would be good if you would take some time to review them, and please let me know if any improvement is needed!
### **Fixes**
1. Fixed **_Trash Can_**'s nbt not synced to client when readded to world after being disassembled.
4. Fixed **_Storage Drawer_**'s upgrades not synced and not recognized by temp handlers.
5. Fixed **_Industrial Foregoing_**'s _Black Hole Unit_ handler holding only 64 items every time assembled into contraptions.

**Comment by juh9870** [comment]
Wow, thanks! I will take a closer look at this later today.
Regarding your two points, I don't remember exactly, so I will answer after I take a look at code again

**Comment by yanang007** [comment]
Thank you for your quick reply! 
After few more tests, here are some conclusions I've made:
1. **_Create_** can handle vanilla double chest correctly. The vanilla double chest will not break when dismounted to world and when mounted with its two parts not glued together ([see here](https://github.com/Creators-of-Create/Create/blob/a92855254c9a7b85ba28781e2e3ce7169549cbf7/src/main/java/com/simibubi/create/content/contraptions/components/structureMovement/Contraption.java#L331-L337)). And as vanilla double chest will not break when dismounted, the code [here](https://github.com/juh9870/MoreMountedStorages/blob/d7a7f8d118f5098f9e0bee26d07b377c9a1b6bdc/src/main/java/com/juh9870/moremountedstorages/helpers/DoubleChestItemStackHandler.java#L87-L96) assuming that they are separated into two inventories will not work as expected where **_otherHandler_** and **_newOtherHandler_** share the same double chest inventory. 
https://github.com/juh9870/MoreMountedStorages/blob/d7a7f8d118f5098f9e0bee26d07b377c9a1b6bdc/src/main/java/com/juh9870/moremountedstorages/helpers/DoubleChestItemStackHandler.java#L87-L96
3. Double chests from **_Expanded Storage_** will break when dismounted from contraption and still need **_DoubleChestItemStackHandler_** to repair it.
4. This is how **_Expanded Storage_** handles with rotation, where _super.rotate_ inherits directly from _BlockBehaviour_ which does nothing. It means that it will not rotate when being as a part of double chest.
```
// ninjaphenix.expandedstorage.block.AbstractChestBlock.rotate
public BlockState rotate(BlockState state, Rotation rotation) {
    return state.getValue(CURSED_CHEST_TYPE) == CursedChestType.SINGLE 
       ? (BlockState)state.setValue(BlockStateProperties.HORIZONTAL_FACING, rotation.rotate((Direction)state.getValue(BlockStateProperties.HORIZONTAL_FACING))) 
       : super.rotate(state, rotation);
}
```

My solution would be:
1. Ignore **_McDoubleChestItemStackHandler_** as Create is able to handle it correctly, which is the current behavior because the **_removeStorageFromWorld_** mixin is injected after **_Create_**'s own code for vanilla chests. Or preserve **_McDoubleChestItemStackHandler_** as a helper to define the priority, making items insert into LEFT chest first as preferred?
2. Use mixin to ensure **_Expanded Storage_** double chests rotating correctly.
3. **_DoubleChestItemStackHandler_** stays the same.

**Comment by juh9870** [comment]
1.18 create doesn't care about order of first/second chest, so I think we shouldn't either. Right now, priority 1 is used by enderchest-like storages, so setting one of the chests to it will mess up insertion ordering. Tho, I think I should move endercehsts into their own priority at like 5, and then double chest insertion priority can be kept

**Comment by yanang007** [comment]
Oh, I see your point. I agree with you that the behavior of double chest should stay the same with Create, because double chest insertion priority seems to add unexpected complexity to this mod. The commit about this should be reverted later.

I am thinking that should there be some extra logic like Create [here](https://github.com/Creators-of-Create/Create/blob/a92855254c9a7b85ba28781e2e3ce7169549cbf7/src/main/java/com/simibubi/create/content/contraptions/components/structureMovement/Contraption.java#L331-L337)? According to my understanding, the logic here is to mount the whole double chest as long as any one of the two chests is glued onto the contraption.

**Vanilla double chest with only right part glued onto contraption.**
v1
v2

**Expanded Storage's double chest with only right part glued onto contraption.**
e1
e2

**Comment by juh9870** [comment]
Wow, this is very useful, thanks! I have some troubles setting up my IDE for minecraft modding, it just broke at one point, I will try to merge as soon as I fix my IDE

**Comment by yanang007** [comment]
I understand you. Java dev environment is just always annoying. Thanks for your attention for this! I didn't mean to take up too much of your time, so no need to rush😉.

**Comment by juh9870** [comment]
I'm really sorry that it's taking so long, I wasn't able to fix my IDE quickly when I was free, amd rn I'm very busy at work, so have no mental power to work on hobby projects. I will really try to look into it more this week

**Comment by yanang007** [comment]
hey, that's just fine. I had a busy month too and left some remaining part unfinished here. Probably finish it later when I'm free.
After all, it's just a hobby to me as well. I'm not in a hurry. It would be good if you care about the comments, but you don't have to. It's okay to just leave it there when not interested.

**Comment by yanang007** [comment]
For anyone who would like to test it out, this is a snapshot build for mc 1.18.2 + create 0.5.0c.
https://jitpack.io/com/github/yanang007/MoreMountedStorages/c77e13ce/MoreMountedStorages-c77e13ce.jar

As for now, versions for mc 1.18.2 + create 0.4 or for mc 1.18.1 is skipped. They may be considered if they are really needed.

**Comment by yanang007** [comment]
For anyone who would like to test it out, there are snapshot builds here.
For mc 1.18.2 + create 0.5.0c. [download](https://jitpack.io/com/github/yanang007/MoreMountedStorages/c77e13ce/MoreMountedStorages-c77e13ce.jar)
For mc 1.18.2 + create 0.5.0.d. [download](https://jitpack.io/com/github/yanang007/MoreMountedStorages/2131529456/MoreMountedStorages-2131529456.jar)

As for now, versions for mc 1.18.2 + create 0.4 or for mc 1.18.1 is skipped. They may be considered if they are really needed.

**Comment by genesy** [comment]
> For anyone who would like to test it out, this is a snapshot build for mc 1.18.2 + create 0.5.0c. [jitpack.io/com/github/yanang007/MoreMountedStorages/c77e13ce/MoreMountedStorages-c77e13ce.jar](https://jitpack.io/com/github/yanang007/MoreMountedStorages/c77e13ce/MoreMountedStorages-c77e13ce.jar)
> 
> As for now, versions for mc 1.18.2 + create 0.4 or for mc 1.18.1 is skipped. They may be considered if they are really needed.

does this work for 0.5d?

**Comment by juh9870** [comment]
Seems like I won't be able to get any free time soon, so @yanang007 if you wish to, you can release MMS port for 1.18.2 as a separate curseforge project, I allow use of any assets in this repository and on old curseforge page.
 If you won't, I will still try to get to this as soon as possible, but no idea when that "soon" will come

**Comment by yanang007** [comment]
@genesy I've made a new version for v0.5.0.d, please refer to my original comment for the download url for the snapshot build.
@juh9870 I will look into it at my free time, but it would still be good if all the versions are held in one project.

**Comment by Lgmrszd** [comment]
> If you won't, I will still try to get to this as soon as possible, but no idea when that "soon" will come

Seems like official port is not planned.

@yanang007 do you plan to release your port? (As separate CurseForge project, as I understood @juh9870 allowed that)
If you don't plan to keep it updated, I can look into becoming your port's maintainer

**Comment by yanang007** [comment]
> > If you won't, I will still try to get to this as soon as possible, but no idea when that "soon" will come
> 
> Seems like official port is not planned.
> 
> @yanang007 do you plan to release your port? (As separate CurseForge project, as I understood @juh9870 allowed that) If you don't plan to keep it updated, I can look into becoming your port's maintainer

That would be great! Feel free to create a fork. I'm totally fine with it as long as @juh9870 agrees.

**Comment by juh9870** [comment]
Hello, yes, you can release it for 1.18 and other versions. I allow reusing icon and other stuff in this repository

**Comment by Lgmrszd** [comment]
> Hello, yes, you can release it for 1.18 and other versions. I allow reusing icon and other stuff in this repository

Okay, I'll be checking the fork and releasing it soon if it's stable

@yanang007 can you give your Curseforge username so I can list you as a contributor?

**Comment by yanang007** [comment]
I appreciate that, but I actually don't have a Curseforge account. You don't have to mention me for that lol.

**Comment by RoboXGamer** [comment]
Will there be a port to 1.19.2?

**Comment by Lgmrszd** [comment]
I'll look into that on this weekend, but I'll publish 1.18.2 version first. I want to test it and make sure everything is all right before releasing it.

**Comment by Lgmrszd** [comment]
CF project got approved, here's the link: https://www.curseforge.com/minecraft/mc-mods/create-mounted-storages
Would appreciate the link in this mod page if that's possible

**Comment by juh9870** [comment]
I've added a link to my project description. Also note, that `alpha` releases can't be added to modpacks

**Comment by Lgmrszd** [comment]
Thanks! I've marked it as `alpha` for now before I test it thoroughly but it looks stable enough so I will change it to beta

**Pull request closed without merging**
